homebrew_packages:
  # init
  - name: ansible
  - name: python
  - name: python3
  - name: mas
  # Shell
  - name: yash
  # GNU
  - name: gawk
  - name: gnu-sed
  - name: coreutils
  - name: findutils
  - name: grep
  # Git
  - name: git
  - name: ghq
  # Terminal
  - name: peco
  - name: exa
  - name: tokei
  - name: pet
  - name: jq
  - name: pwgen
  - name: moreutils
  - name: nkf
  # develop
  - name: direnv
  - name: heroku
  - name: azure-cli
  - name: tfenv
  - name: shellcheck
  # Media
  - name: youtube-dl
  - name: ffmpeg
  - name: zopfli
  # エディタ
  - name: vim
  # curl
  - name: openssl
  - name: curl
    option: with-openssl
