- name: defaults type bool
  osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: bool
    value: '{{ item.value }}'
    state: present
  with_items: '{{ defaults_bool }}'

- name: defaults type string
  osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: string
    value: '{{ item.value }}'
    state: present
  with_items: '{{ defaults_string }}'
